kind: pipeline
type: docker
name: gopay

platform:
  os: linux
  arch: amd64

steps:
  - name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "gopay"
    commands:
      - mysql --version

  - name: test
    image: golang:1.13
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      CGO_ENABLED: "0"
      GOOS: "linux"
    commands:
      - go version
      - go env
      - go test ./...
      - mysql -u root -p root

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag
